name: umiuni2d_io_flutter
description: A new Flutter project.
version: 0.0.1
author:
homepage:

dependencies:
  flutter:
    sdk: flutter
  umiuni2d_io:
    git:
      url: https://github.com/kyorohiro/umiuni2d_io.git
      ref: v0.0.2
  umiuni2d_io_dartio:
    git:
      url: https://github.com/kyorohiro/umiuni2d_io_dartio.git
      ref: v0.0.2
  path: 1.5.1
flutter:
  plugin:
    androidPackage: net.umiuni2d.umiuni2dioflutter
    pluginClass: Umiuni2dIoFlutterPlugin
