name: umiuni2d_io_flutter
description: A new Flutter project.
version: 0.0.1
author:
homepage:

dependencies:
  flutter:
    sdk: flutter
  umiuni2d_platform_path:
    git: https://github.com/kyorohiro/umiuni2d_platform_path.git
  umiuni2d_io:
    git: https://github.com/kyorohiro/umiuni2d_io.git
  path: 1.5.1
flutter:
  plugin:
    androidPackage: net.umiuni2d.umiuni2dioflutter
    pluginClass: Umiuni2dIoFlutterPlugin
